{{ config(materialized='table') }}

with source_data as (

   SELECT LOCATION,
   ROUND(SUM(GROWTH_FACTOR_OF_NEW_DEATHS)/COUNT(LOCATION),2) GROWTH_FACTOR_OF_NEW_DEATHS,
  ROUND(SUM(GROWTH_FACTOR_OF_NEW_CASES)/COUNT(LOCATION),2) GROWTH_FACTOR_OF_NEW_CASES
   FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL
   GROUP BY 1  

)

select *
from source_data