{{ config(materialized='table') }}

with source_data as (

   SELECT DISTINCT(LATITUDE),LONGITUDE,
   CONTINENT,COUNTRY,LOCATION_LEVEL,LOCATION, 
   LOCATION_ISO_CODE,

   AREA_KM_2_ as AREA_KM_SQUARE,
   TOTAL_URBAN_VILLAGES,TOTAL_DISTRICTS,TOTAL_REGENCIES,TOTAL_CITIES,POPULATION, POPULATION_DENSITY
           FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL 
          
)

select *
from source_data