{{ config(materialized='table') }}

with source_data as (

   SELECT MAX(LATITUDE) LATITUDE,
   MAX(LONGITUDE) LONGITUDE,
   CONTINENT,COUNTRY,LOCATION_LEVEL,LOCATION, 
   LOCATION_ISO_CODE,
   MAX(AREA_KM_2_) as AREA_KM_SQUARE,
   MAX(TOTAL_URBAN_VILLAGES) TOTAL_URBAN_VILLAGES,
   MAX(TOTAL_DISTRICTS) TOTAL_DISTRICTS,
   MAX(TOTAL_REGENCIES) TOTAL_REGENCIES,
   MAX(TOTAL_CITIES) TOTAL_CITIES,MAX(POPULATION) POPULATION,MAX( POPULATION_DENSITY)
   POPULATION_DENSITY FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL
    GROUP BY  
   CONTINENT,COUNTRY,LOCATION_LEVEL,LOCATION, 
   LOCATION_ISO_CODE
          
)

select *
from source_data