{{ config(materialized='table') }}

with source_data as (

   SELECT LOCATION_LEVEL,PROVINCE ,
    SUM(TOTAL_ACTIVE_CASES) TOTAL_ACTIVE_CASES,
       SUM(TOTAL_RECOVERED) TOTAL_RECOVERED,
       SUM(TOTAL_DEATHS) TOTAL_DEATHS,
        SUM(TOTAL_CASES) TOTAL_CASES,
        SUM(TOTAL_CASES_PER_MILLION) TOTAL_CASES_PER_MILLION,
         SUM(TOTAL_DEATHS_PER_MILLION) TOTAL_DEATHS_PER_MILLION  
           FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL 
             GROUP BY 1,2 ORDER BY 1 DESC  

)

select *
from source_data