{{ config(materialized='table') }}

with source_data as (

   SELECT DATE_TRUNC(WEEK ,TO_DATE(DATE,'MM/DD/YYYY'))  WEEK_START_DATE ,
    SUM(TOTAL_ACTIVE_CASES) TOTAL_ACTIVE_CASES,
       SUM(TOTAL_RECOVERED) TOTAL_RECOVERED,
       SUM(TOTAL_DEATHS) TOTAL_DEATHS,
        SUM(TOTAL_CASES) TOTAL_CASES,
        SUM(TOTAL_CASES_PER_MILLION) TOTAL_CASES_PER_MILLION,
         SUM(TOTAL_DEATHS_PER_MILLION) TOTAL_DEATHS_PER_MILLION  
           FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL 
           GROUP BY  DATE_TRUNC(WEEK ,TO_DATE(DATE,'MM/DD/YYYY'))  ORDER BY 1 DESC 

)

select *
from source_data