{{ config(materialized='table') }}

with source_data as (

   SELECT DATE_TRUNC(YEAR ,TO_DATE(DATE,'MM/DD/YYYY')) YEAR_START_DATE ,
    SUM(NEW_CASES) NEW_CASES,
       SUM(NEW_ACTIVE_CASES) NEW_ACTIVE_CASES,
       SUM(NEW_RECOVERED) NEW_RECOVERED,
        SUM(NEW_DEATHS) NEW_DEATHS,
        SUM(NEW_CASES_PER_MILLION) NEW_CASES_PER_MILLION,
         SUM(NEW_DEATHS_PER_MILLION) NEW_DEATHS_PER_MILLION  
           FROM FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_DEEPANSHU_GOYAL 
           GROUP BY DATE_TRUNC(YEAR ,TO_DATE(DATE,'MM/DD/YYYY')) ORDER BY 1 DESC 

)

select *
from source_data